import sys
import os
import asyncio
import json
from typing import List, Dict, Any
from pydantic import BaseModel, Field

# Ensure deploy-squad is in system path for modular imports
current_dir = os.path.dirname(os.path.abspath(__file__))
if current_dir not in sys.path:
    sys.path.append(current_dir)

from google.antigravity import Agent, LocalAgentConfig

# Importing module-specific schemas
from agents.code_reviewer.schema import CodeReviewReport
from agents.ml_guardian.schema import MLOpsReport
from agents.iso_compliance.schema import ISOComplianceReport

# Importing tools
from agents.code_reviewer.tools import run_linter, get_git_diff
from agents.ml_guardian.tools import check_mlflow_metrics, validate_snowflake_schema, verify_rag_vector_index, verify_llm_notetaking_prompts, verify_mlops_pipeline_structure
from agents.iso_compliance.tools import check_env_security_compliance

class FinalExecutiveReport(BaseModel):
    status: str = Field(description="Final deployment decision verdict: 'APPROVED', 'APPROVED_WITH_WARNINGS', or 'REJECTED'.")
    summary: str = Field(description="High-level executive summary consolidating findings from Engineering, MLOps, and ISO Compliance.")
    blocking_issues: List[str] = Field(default=[], description="Compiled list of critical blockers halting production deployment.")
    innovation_backlog: List[Dict[str, Any]] = Field(default=[], description="Aggregated innovation ideas generated by the council.")

def build_application_snapshot(project_root: str) -> str:
    snapshot = []
    # We will scan three main directories
    scan_dirs = ["src-python", "src", "src-tauri"]
    
    for folder_name in scan_dirs:
        folder_path = os.path.join(project_root, folder_name)
        if not os.path.exists(folder_path):
            continue
            
        snapshot.append(f"\n=========================================\n=== DIRECTORY: {folder_name} ===\n=========================================\n")
        
        for root, dirs, files in os.walk(folder_path):
            # Exclude large/binary build directories and hidden folders
            dirs[:] = [
                d for d in dirs 
                if not d.startswith(".") 
                and d not in ("__pycache__", "node_modules", "target", "dist", "build", "out")
            ]
            
            for file in files:
                if file.startswith("."):
                    continue
                # Supported file extensions
                if not file.endswith((".py", ".json", ".txt", ".toml", ".ts", ".tsx", ".rs", ".css")):
                    continue
                    
                file_path = os.path.join(root, file)
                rel_path = os.path.relpath(file_path, project_root)
                
                try:
                    with open(file_path, "r", encoding="utf-8") as f:
                        content = f.read()
                    snapshot.append(f"=== FILE: {rel_path} ===\n{content}\n")
                except Exception as e:
                    snapshot.append(f"=== FILE: {rel_path} (FAILED TO READ: {str(e)}) ===\n")
                    
    return "\n".join(snapshot)

async def run_specialized_agent(skill_path: str, response_schema: Any, tools: List[Any], context_data: str) -> str:
    config = LocalAgentConfig()
    abs_skill_path = os.path.join(current_dir, skill_path)
    with open(abs_skill_path, "r", encoding="utf-8") as f:
        system_instruction = f.read()

    async with Agent(config, tools=tools) as agent:
        prompt = f"Perform a comprehensive evaluation on the following software snapshot:\n\n{context_data}"
        response = await agent.chat(
            prompt,
            system_instruction=system_instruction,
            response_schema=response_schema
        )
        return await response.text()

async def main():
    # Configure stdout to use UTF-8 if available, or ignore errors
    try:
        sys.stdout.reconfigure(encoding='utf-8')
    except Exception:
        pass

    project_root = os.path.abspath(os.path.join(current_dir, ".."))
    print(f"[SCAN] Scanning codebases in {project_root}...")
    application_snapshot = build_application_snapshot(project_root)
    
    print("[SDK] Dispatched 3 parallel evaluation agents via Antigravity 2.0 Engine...")
    
    # Concurrent Execution via Fan-Out Pattern (Now with 3 Agents!)
    code_task = run_specialized_agent(
        "agents/code_reviewer/prompt.md", 
        CodeReviewReport, 
        [run_linter, get_git_diff], 
        application_snapshot
    )
    ml_task = run_specialized_agent(
        "agents/ml_guardian/prompt.md", 
        MLOpsReport, 
        [check_mlflow_metrics, validate_snowflake_schema, verify_rag_vector_index, verify_llm_notetaking_prompts, verify_mlops_pipeline_structure], 
        application_snapshot
    )
    iso_task = run_specialized_agent(
        "agents/iso_compliance/prompt.md", 
        ISOComplianceReport, 
        [check_env_security_compliance], 
        application_snapshot
    )

    # Await all 3 concurrent execution tasks smoothly
    report_code, report_ml, report_iso = await asyncio.gather(code_task, ml_task, iso_task)

    print("\n[ORCHESTRATE] Consolidating subagent intelligence inside Central Orchestrator...")
    
    orchestrator_input = f"""
    Code Reviewer Subagent Report:
    {report_code}
    
    ML Guardian Subagent Report:
    {report_ml}
    
    ISO Compliance Subagent Report:
    {report_iso}
    """

    async with Agent(LocalAgentConfig()) as orchestrator:
        final_verdict = await orchestrator.chat(
            f"Consolidate the provided subagent analyses. Resolve data conflicts and populate the schema:\n\n{orchestrator_input}",
            system_instruction="You are the Principal Systems Architect. Evaluate inputs from specialized subagents (Engineering, MLOps, Regulations), decide if production deployment is blocked, and compile all forward-looking innovation backlog ideas.",
            response_schema=FinalExecutiveReport
        )
        
        verdict_text = await final_verdict.text()
        print("\n============ FINAL EXECUTIVE DEPLOYMENT REPORT ============")
        print(verdict_text)

        # Write to JSON file
        reports_dir = os.path.join(current_dir, "reports")
        os.makedirs(reports_dir, exist_ok=True)
        report_path = os.path.join(reports_dir, "latest_report.json")
        try:
            parsed_json = json.loads(verdict_text)
            with open(report_path, "w", encoding="utf-8") as rf:
                json.dump(parsed_json, rf, indent=2)
        except Exception:
            with open(report_path, "w", encoding="utf-8") as rf:
                rf.write(verdict_text)
        print(f"\n[SAVE] Saved consolidated executive report to: {report_path}")

if __name__ == "__main__":
    asyncio.run(main())